{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "Comment",
    "version" : "1.0.0"
  },
  "paths" : {
    "/portal/api/communityTopics/{topicId}/comments/{parentCommentId}/replies" : {
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Add Reply",
        "description" : "Add reply to a comment",
        "operationId" : "addReply",
        "parameters" : [ {
          "$ref" : "#/components/parameters/topicId"
        }, {
          "$ref" : "#/components/parameters/parentCommentId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/communityCommentJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/commentReply"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "SubEntityCreate_Policy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.addReply"
        }
      }
    },
    "/portal/api/communityUsers/{userId}/comments" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "Get User Comments",
        "description" : "to get all the community comments published by a user",
        "operationId" : "getUserComments",
        "parameters" : [ {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/startTime"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "$ref" : "#/components/parameters/endTime"
        }, {
          "$ref" : "#/components/parameters/categoryId"
        }, {
          "$ref" : "#/components/parameters/userId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getUserCommentsResponse"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.getUserComments"
        }
      }
    },
    "/portal/api/communityTopics/{topicId}/comments/{parentCommentId}/replies/{commentId}" : {
      "put" : {
        "tags" : [ "Comment" ],
        "summary" : "Update Reply",
        "description" : "Update a reply",
        "operationId" : "updateReply",
        "parameters" : [ {
          "$ref" : "#/components/parameters/topicId"
        }, {
          "$ref" : "#/components/parameters/parentCommentId"
        }, {
          "$ref" : "#/components/parameters/commentId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateReply_communityCommentJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/commentReply"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "EntityUpdateAndDelete_Policy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.updateReply"
        }
      }
    },
    "/portal/api/communityTopics/{topicId}/comments" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "List All Comments",
        "description" : "API to get comments of a Topic",
        "operationId" : "listAllComments",
        "parameters" : [ {
          "name" : "isDescending",
          "in" : "query",
          "description" : "Sort list of comments by Ascending or Descending",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "boolean", "null" ],
            "description" : "Sort list of comments by Ascending or Descending"
          }
        }, {
          "$ref" : "#/components/parameters/limit"
        }, {
          "$ref" : "#/components/parameters/from"
        }, {
          "$ref" : "#/components/parameters/topicId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/listAllComment"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 60,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.getComments"
        }
      },
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Add  Comment",
        "description" : "Add Comment To a Topic",
        "operationId" : "addComment",
        "parameters" : [ {
          "$ref" : "#/components/parameters/topicId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/addComment_communityCommentJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/commentResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "SubEntityCreate_Policy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.addComment"
        }
      }
    },
    "/portal/api/communityUsers/{userId}/topicCommentTrend" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "Topic Comment Trend",
        "description" : "to get topic comment trend of a user for specific period of time",
        "operationId" : "topicCommentTrend",
        "parameters" : [ {
          "name" : "reportFor",
          "in" : "query",
          "description" : "For selecting date range. Values can be WEEK (or) MONTH (or) YEAR (or) SPECIFIC_DATE_RANGE",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : [ "string", "null" ],
            "description" : "For selecting date range. Values can be WEEK (or) MONTH (or) YEAR (or) SPECIFIC_DATE_RANGE",
            "enum" : [ "WEEK", "MONTH", "YEAR", "SPECIFIC_DATE_RANGE" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        }, {
          "$ref" : "#/components/parameters/startTime"
        }, {
          "$ref" : "#/components/parameters/endTime"
        }, {
          "$ref" : "#/components/parameters/categoryId"
        }, {
          "$ref" : "#/components/parameters/userId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/topicCommentTrend"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.reports.CommunityPortalReportService.getTopicResponseTrend"
        }
      }
    },
    "/portal/api/communityTopics/{topicId}/comments/{commentId}" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "Get Comment ",
        "description" : "Get a Comment",
        "operationId" : "getComment",
        "parameters" : [ {
          "$ref" : "#/components/parameters/topicId"
        }, {
          "$ref" : "#/components/parameters/commentId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getComment"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.remoteip"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.getComment"
        }
      },
      "put" : {
        "tags" : [ "Comment" ],
        "summary" : "Update a Comment",
        "description" : "Update a Comment",
        "operationId" : "updateComment",
        "parameters" : [ {
          "$ref" : "#/components/parameters/topicId"
        }, {
          "$ref" : "#/components/parameters/commentId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/portalId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateComment_communityCommentJson"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/commentResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/invalidDataErrorResponse"
          }
        },
        "security" : [ {
          "jwt-oauth" : [ "jwt-oauth" ]
        } ],
        "x-audience" : [ "external-public" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "policy" : "EntityUpdateAndDelete_Policy"
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "apimethod" : "com.zoho.desk.helpcenter.community.responses.CommentPortalRestService.updateComment"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "attachmentDetails" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "size" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "id", "name", "size" ]
      },
      "attachments" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./Comment.json#/components/schemas/attachmentDetails"
        }
      },
      "creator" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "photoUrl" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 200,
            "minLength" : 0,
            "pattern" : "([0-9a-zA-Z_\\-\\.\\$@\\?\\,\\:\\'\\/\\!\\P{InBasicLatin}\\s])+"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "label" : {
            "$ref" : "./Label.json#/components/schemas/labelMetaResponse"
          },
          "type" : {
            "type" : [ "string", "null" ],
            "enum" : [ "ENDUSER", "SUPPORTREP" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "id", "label", "name", "photoUrl", "type" ]
      },
      "commentResponseCommonValues" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "creator" : {
            "$ref" : "./Comment.json#/components/schemas/creator"
          },
          "mentions" : {
            "$ref" : "./Mentions.json#/components/schemas/mentionedObj"
          },
          "createdTime" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
          },
          "modifiedBy" : {
            "$ref" : "./Comment.json#/components/schemas/creator"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "content" : {
            "type" : [ "string", "null" ],
            "maxLength" : 50000,
            "minLength" : 0,
            "x-custom-parameters-attributes" : {
              "removeExif" : false,
              "replacementString" : "",
              "filterMatchedContent" : false,
              "antivirus" : false,
              "allowInvalid" : false,
              "descrption" : "",
              "secret" : false,
              "preserveCharsLimit" : 10,
              "trim" : false,
              "internalParam" : false,
              "preserveChars" : "0,5",
              "xss" : "antisamyfilter_custom",
              "importUrl" : false,
              "decrypt" : false
            }
          },
          "status" : {
            "type" : [ "string", "null" ],
            "enum" : [ "AWAITINGAPPROVAL", "PUBLISHED", "TRASHED", "SPAM" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "content", "createdTime", "creator", "id", "mentions", "modifiedBy", "status" ]
      },
      "commentResponse" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "./Comment.json#/components/schemas/commentResponseCommonValues"
        }, {
          "type" : [ "object", "null" ],
          "properties" : {
            "modifiedTime" : {
              "type" : [ "string", "null" ],
              "maxLength" : 100,
              "minLength" : 0,
              "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
            },
            "attachments" : {
              "$ref" : "./Comment.json#/components/schemas/attachments"
            }
          },
          "required" : [ "attachments", "modifiedTime" ]
        } ]
      },
      "getUserComments" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "creator" : {
            "$ref" : "./Comment.json#/components/schemas/creator"
          },
          "topicId" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "subject" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "createdTime" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
          },
          "topicPermalink" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "[a-zA-Z0-9%\\-._/?\\P{InBasicLatin}]*"
          },
          "modifiedBy" : {
            "$ref" : "./Comment.json#/components/schemas/creator"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "type" : {
            "type" : [ "string", "null" ],
            "enum" : [ "DISCUSSION", "ANNOUNCEMENT", "QUESTION", "IDEA", "PROBLEM" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "content" : {
            "type" : [ "string", "null" ],
            "maxLength" : 50000,
            "minLength" : 0
          },
          "status" : {
            "type" : [ "string", "null" ],
            "enum" : [ "AWAITINGAPPROVAL", "PUBLISHED", "TRASHED", "SPAM" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "content", "createdTime", "creator", "id", "modifiedBy", "status", "subject", "topicId", "topicPermalink", "type" ]
      },
      "getUserCommentsData" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./Comment.json#/components/schemas/getUserComments"
        }
      },
      "repliesData" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./Comment.json#/components/schemas/commentResponse"
        }
      },
      "getComment" : {
        "additionalProperties" : false,
        "allOf" : [ {
          "$ref" : "./Comment.json#/components/schemas/commentResponse"
        }, {
          "type" : [ "object", "null" ],
          "properties" : {
            "replies" : {
              "$ref" : "./Comment.json#/components/schemas/repliesData"
            }
          },
          "required" : [ "replies" ]
        } ]
      },
      "topicCommentTrendDetails" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "date" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "count" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "count", "date" ]
      },
      "postTrend" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./Comment.json#/components/schemas/topicCommentTrendDetails"
        }
      },
      "commentTrend" : {
        "type" : [ "array", "null" ],
        "items" : {
          "$ref" : "./Comment.json#/components/schemas/topicCommentTrendDetails"
        }
      },
      "topicCommentTrendData" : {
        "type" : [ "object", "null" ],
        "additionalProperties" : false,
        "properties" : {
          "postTrend" : {
            "$ref" : "./Comment.json#/components/schemas/postTrend"
          },
          "commentTrend" : {
            "$ref" : "./Comment.json#/components/schemas/commentTrend"
          }
        },
        "required" : [ "commentTrend", "postTrend" ]
      }
    },
    "responses" : {
      "commentReply" : {
        "description" : "commentReply template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "additionalProperties" : false,
              "allOf" : [ {
                "$ref" : "./Comment.json#/components/schemas/commentResponse"
              }, {
                "type" : [ "object", "null" ],
                "properties" : {
                  "modifiedTime" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
                  },
                  "attachments" : {
                    "$ref" : "./Comment.json#/components/schemas/attachments"
                  }
                },
                "required" : [ "attachments", "modifiedTime" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "creator" : {
                    "photoUrl" : null,
                    "name" : "User - 1",
                    "id" : "4000000008734",
                    "label" : {
                      "preferences" : {
                        "shape" : "RECTANGLE",
                        "bgColor" : "#23F123",
                        "textColor" : "#2CA123"
                      },
                      "name" : "Admin",
                      "id" : "6000000158001",
                      "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                    },
                    "type" : "ENDUSER"
                  },
                  "attachments" : [ {
                    "size" : "1024",
                    "name" : "New Attachment.jpeg",
                    "id" : "8651"
                  } ],
                  "createdTime" : "2013-11-04T11:21:07.000Z",
                  "id" : "1005",
                  "content" : "This is my first reply to a comment"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "getUserCommentsResponse" : {
        "description" : "getUserCommentsResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "./Comment.json#/components/schemas/getUserCommentsData"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "creator" : {
                      "photoUrl" : null,
                      "name" : "User - 1",
                      "id" : "5000000029005",
                      "label" : {
                        "preferences" : {
                          "shape" : "RECTANGLE",
                          "bgColor" : "#23F123",
                          "textColor" : "#2CA123"
                        },
                        "name" : "Admin",
                        "id" : "6000000158001",
                        "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                      },
                      "type" : "SUPPORTREP"
                    },
                    "topicId" : "27000000004034",
                    "createdTime" : "2017-04-03T13:33:33.466Z",
                    "topicPermalink" : "posting-a-new-topic-through-rest-api-3-4-2017",
                    "id" : "27000000004045",
                    "content" : "<div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div>",
                    "topicType" : "IDEA",
                    "topicTitle" : "(Updated) Posting a new topic through REST API.",
                    "status" : "PUBLISHED"
                  }, {
                    "creator" : {
                      "photoUrl" : null,
                      "name" : "User - 1",
                      "id" : "5000000029005",
                      "label" : {
                        "preferences" : {
                          "shape" : "RECTANGLE",
                          "bgColor" : "#23F123",
                          "textColor" : "#2CA123"
                        },
                        "name" : "Admin",
                        "id" : "6000000158001",
                        "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                      },
                      "type" : "SUPPORTREP"
                    },
                    "topicId" : "27000000004007",
                    "createdTime" : "2017-04-03T13:09:03.467Z",
                    "topicPermalink" : "posting-a-new-topic-through-rest-api",
                    "id" : "27000000004030",
                    "content" : "<div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div><div>Posting a new topic through REST API.</div>",
                    "topicType" : "IDEA",
                    "topicTitle" : "(Updated) Posting a new topic through REST API.",
                    "status" : "PUBLISHED"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "listAllComment" : {
        "description" : "listAllComment template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "allOf" : [ {
                "type" : "array",
                "items" : {
                  "type" : "object",
                  "properties" : {
                    "attachments" : {
                      "type" : [ "null", "array" ],
                      "items" : {
                        "type" : [ "null", "object" ],
                        "additionalProperties" : false,
                        "maxProperties" : 3,
                        "minProperties" : 3,
                        "properties" : {
                          "size" : {
                            "type" : [ "string", "null", "integer" ],
                            "format" : "int64",
                            "pattern" : "([0-9]+)"
                          },
                          "name" : {
                            "type" : [ "string", "null" ],
                            "maxLength" : 100,
                            "minLength" : 0
                          },
                          "id" : {
                            "type" : [ "string", "null", "integer" ],
                            "format" : "int64",
                            "pattern" : "([0-9]+)"
                          }
                        },
                        "required" : [ "id", "name", "size" ]
                      },
                      "uniqueItems" : false
                    }
                  }
                }
              }, {
                "type" : [ "array", "null" ],
                "items" : {
                  "$ref" : "./Comment.json#/components/schemas/getComment"
                }
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "modifiedTime" : "2015-09-28T08:23:25.688Z",
                    "creator" : {
                      "photoUrl" : null,
                      "name" : "User - 1",
                      "id" : "4000000008734",
                      "label" : {
                        "preferences" : {
                          "shape" : "RECTANGLE",
                          "bgColor" : "#23F123",
                          "textColor" : "#2CA123"
                        },
                        "name" : "Admin",
                        "id" : "6000000158001",
                        "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                      },
                      "type" : "ENDUSER"
                    },
                    "attachments" : [ {
                      "size" : "1024",
                      "name" : "New Attachment.jpeg",
                      "id" : "8651"
                    } ],
                    "replies" : [ ],
                    "createdTime" : "2013-11-04T11:21:07.000Z",
                    "id" : "100001",
                    "content" : "Welcome to Zoho",
                    "status" : "PUBLISHED"
                  }, {
                    "modifiedTime" : "2015-09-28T08:23:25.688Z",
                    "creator" : {
                      "photoUrl" : null,
                      "name" : "User - 1",
                      "id" : "4000000008734",
                      "label" : {
                        "preferences" : {
                          "shape" : "RECTANGLE",
                          "bgColor" : "#23F123",
                          "textColor" : "#2CA123"
                        },
                        "name" : "Admin",
                        "id" : "6000000158001",
                        "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                      },
                      "type" : "ENDUSER"
                    },
                    "attachments" : [ {
                      "size" : "1024",
                      "name" : "New Attachment.jpeg",
                      "id" : "8651"
                    } ],
                    "replies" : [ ],
                    "createdTime" : "2013-11-04T11:21:07.000Z",
                    "id" : "100002",
                    "content" : "Zoho Desk-Put customer service at the heart of your company",
                    "status" : "PUBLISHED"
                  }, {
                    "modifiedTime" : "2015-09-28T08:23:25.688Z",
                    "attachments" : [ {
                      "size" : "1024",
                      "name" : "New Attachment.jpeg",
                      "id" : "8651"
                    } ],
                    "replies" : [ {
                      "modifiedTime" : "2015-09-28T08:23:25.688Z",
                      "creator" : {
                        "photoUrl" : null,
                        "name" : "User - 1",
                        "id" : "4000000008734",
                        "label" : {
                          "preferences" : {
                            "shape" : "RECTANGLE",
                            "bgColor" : "#23F123",
                            "textColor" : "#2CA123"
                          },
                          "name" : "Admin",
                          "id" : "6000000158001",
                          "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                        },
                        "type" : "ENDUSER"
                      },
                      "attachments" : [ {
                        "size" : "1024",
                        "name" : "New Attachment.jpeg",
                        "id" : "8651"
                      } ],
                      "createdTime" : "2013-11-04T11:21:07.000Z",
                      "id" : "1005",
                      "content" : "My first reply",
                      "status" : "PUBLISHED"
                    } ],
                    "creatorId" : "4000006",
                    "createdTime" : "2013-11-04T11:21:07.000Z",
                    "id" : "1004",
                    "content" : "This is a new Comment",
                    "status" : "PUBLISHED"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "topicCommentTrend" : {
        "description" : "topicCommentTrend template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "./Comment.json#/components/schemas/topicCommentTrendData"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : {
                    "postTrend" : [ {
                      "date" : "12-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "13-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "14-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "15-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "16-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "17-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "18-Apr-2017",
                      "count" : "0"
                    } ],
                    "commentTrend" : [ {
                      "date" : "12-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "13-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "14-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "15-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "16-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "17-Apr-2017",
                      "count" : "0"
                    }, {
                      "date" : "18-Apr-2017",
                      "count" : "0"
                    } ]
                  }
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "getComment" : {
        "description" : "getComment template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "allOf" : [ {
                "type" : "object",
                "properties" : {
                  "attachments" : {
                    "type" : [ "null", "array" ],
                    "items" : {
                      "type" : [ "null", "object" ],
                      "additionalProperties" : false,
                      "maxProperties" : 3,
                      "minProperties" : 3,
                      "properties" : {
                        "size" : {
                          "type" : [ "string", "null", "integer" ],
                          "format" : "int64",
                          "pattern" : "([0-9]+)"
                        },
                        "name" : {
                          "type" : [ "string", "null" ],
                          "maxLength" : 100,
                          "minLength" : 0
                        },
                        "id" : {
                          "type" : [ "string", "null", "integer" ],
                          "format" : "int64",
                          "pattern" : "([0-9]+)"
                        }
                      },
                      "required" : [ "id", "name", "size" ]
                    },
                    "uniqueItems" : false
                  }
                }
              }, {
                "additionalProperties" : false,
                "allOf" : [ {
                  "$ref" : "./Comment.json#/components/schemas/commentResponse"
                }, {
                  "type" : [ "object", "null" ],
                  "properties" : {
                    "replies" : {
                      "$ref" : "./Comment.json#/components/schemas/repliesData"
                    }
                  },
                  "required" : [ "replies" ]
                } ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "modifiedTime" : "2019-03-05T10:50:03.387Z",
                  "creator" : {
                    "photoUrl" : null,
                    "name" : "User - 1",
                    "id" : "4000000008734",
                    "label" : {
                      "preferences" : {
                        "shape" : "RECTANGLE",
                        "bgColor" : "#23F123",
                        "textColor" : "#2CA123"
                      },
                      "name" : "Admin",
                      "id" : "6000000158001",
                      "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                    },
                    "type" : "ENDUSER"
                  },
                  "attachments" : [ {
                    "size" : "1024",
                    "name" : "New Attachment.jpeg",
                    "id" : "8651"
                  } ],
                  "replies" : [ {
                    "modifiedTime" : "2019-03-05T10:50:03.387Z",
                    "creator" : {
                      "photoUrl" : null,
                      "name" : "User - 1",
                      "id" : "4000000008734",
                      "label" : {
                        "preferences" : {
                          "shape" : "RECTANGLE",
                          "bgColor" : "#23F123",
                          "textColor" : "#2CA123"
                        },
                        "name" : "Admin",
                        "id" : "6000000158001",
                        "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                      },
                      "type" : "ENDUSER"
                    },
                    "attachments" : [ {
                      "size" : "1024",
                      "name" : "New Attachment.jpeg",
                      "id" : "8651"
                    } ],
                    "createdTime" : "2013-11-04T11:21:07.000Z",
                    "id" : "1005",
                    "content" : "My first reply",
                    "status" : "PUBLISHED"
                  } ],
                  "createdTime" : "2013-11-04T11:21:07.000Z",
                  "id" : "1004",
                  "content" : "This is a new Comment",
                  "status" : "PUBLISHED"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "commentResponse" : {
        "description" : "commentResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "additionalProperties" : false,
              "allOf" : [ {
                "$ref" : "./Comment.json#/components/schemas/commentResponseCommonValues"
              }, {
                "type" : [ "object", "null" ],
                "properties" : {
                  "modifiedTime" : {
                    "type" : [ "string", "null" ],
                    "maxLength" : 100,
                    "minLength" : 0,
                    "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
                  },
                  "attachments" : {
                    "$ref" : "./Comment.json#/components/schemas/attachments"
                  }
                },
                "required" : [ "attachments", "modifiedTime" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "creator" : {
                    "photoUrl" : null,
                    "name" : "User - 1",
                    "id" : "4000000008734",
                    "label" : {
                      "preferences" : {
                        "shape" : "RECTANGLE",
                        "bgColor" : "#23F123",
                        "textColor" : "#2CA123"
                      },
                      "name" : "Admin",
                      "id" : "6000000158001",
                      "logoUrl" : "https://desk.zoho.com/portal/api/publicImages/6000000158231?orgId=14132"
                    },
                    "type" : "ENDUSER"
                  },
                  "attachments" : [ {
                    "size" : "1024",
                    "name" : "New Attachment.jpeg",
                    "id" : "8651"
                  } ],
                  "createdTime" : "2013-11-04T11:21:07.000Z",
                  "id" : "1004",
                  "content" : "Last Comment"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : {
      "topicId" : {
        "name" : "topicId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "limit" : {
        "name" : "limit",
        "in" : "query",
        "description" : "number of objects to list.",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int32",
          "description" : "number of objects to list.",
          "maximum" : 100,
          "minimum" : 1,
          "pattern" : "([0-9]+)"
        }
      },
      "parentCommentId" : {
        "name" : "parentCommentId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "commentId" : {
        "name" : "commentId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "startTime" : {
        "name" : "startTime",
        "in" : "query",
        "description" : "Start time of user Comments. Start time should be in GMT time zone",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null" ],
          "description" : "Start time of user Comments. Start time should be in GMT time zone",
          "maxLength" : 100,
          "minLength" : 0,
          "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
        }
      },
      "from" : {
        "name" : "from",
        "in" : "query",
        "description" : "Index from which list is retrieved and it starts from 1",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int32",
          "description" : "Index from which list is retrieved and it starts from 1",
          "pattern" : "([0-9]+)"
        }
      },
      "endTime" : {
        "name" : "endTime",
        "in" : "query",
        "description" : "end time of user Comments. End time should be in GMT time zone",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null" ],
          "description" : "end time of user Comments. End time should be in GMT time zone",
          "maxLength" : 100,
          "minLength" : 0,
          "pattern" : "(((19|20)\\d\\d)[-/.]{1}(0?[1-9]|1[012])[-/.]{1}(0?[1-9]|[12][0-9]|3[01])(T)([01]?[0-9]|2[0-3]):[0-5]?[0-9]:[0-5]?[0-9]([/.][\\d]{0,3})?(Z))"
        }
      },
      "userId" : {
        "name" : "userId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "categoryId" : {
        "name" : "categoryId",
        "in" : "query",
        "description" : "id of a category",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "description" : "id of a category",
          "pattern" : "([0-9]+)"
        }
      }
    },
    "requestBodies" : {
      "communityCommentJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "attachmentIds" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : [ { } ]
                  },
                  "uniqueItems" : false
                },
                "content" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 50000,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "xss" : "antisamyfilter_custom"
                  }
                },
                "notifyMentions" : {
                  "type" : [ "boolean", "null" ],
                  "description" : "whether to notify mentioned user while updateing content."
                }
              },
              "required" : [ "content" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "attachmentIds" : [ "8651" ],
                  "content" : "My first reply"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "updateReply_communityCommentJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "attachmentIds" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : [ { } ]
                  },
                  "uniqueItems" : false
                },
                "content" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 50000,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "xss" : "antisamyfilter_custom"
                  }
                },
                "notifyMentions" : {
                  "type" : [ "boolean", "null" ],
                  "description" : "whether to notify mentioned user while updateing content."
                }
              },
              "required" : [ "content" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "attachmentIds" : [ "8651" ],
                  "content" : "This is my first reply to a comment"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "addComment_communityCommentJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "attachmentIds" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : [ { } ]
                  },
                  "uniqueItems" : false
                },
                "content" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 50000,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "xss" : "antisamyfilter_custom"
                  }
                },
                "notifyMentions" : {
                  "type" : [ "boolean", "null" ],
                  "description" : "whether to notify mentioned user while updateing content."
                }
              },
              "required" : [ "content" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "attachmentIds" : [ "8651" ],
                  "content" : "My First Comment"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "updateComment_communityCommentJson" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "object", "null" ],
              "additionalProperties" : false,
              "properties" : {
                "attachmentIds" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : [ { } ]
                  },
                  "uniqueItems" : false
                },
                "content" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 50000,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "xss" : "antisamyfilter_custom"
                  }
                },
                "notifyMentions" : {
                  "type" : [ "boolean", "null" ],
                  "description" : "whether to notify mentioned user while updateing content."
                }
              },
              "required" : [ "content" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "attachmentIds" : [ "8651" ],
                  "content" : "Last Comment"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "jwt-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/jwt-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "Comment"
}