{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "AssistInteg",
    "version" : "1.0.0",
    "x-clan-group" : "integration",
    "x-module-group" : "integration"
  },
  "paths" : {
    "/api/v1/zohoAssist/permissions" : {
      "get" : {
        "tags" : [ "AssistInteg" ],
        "summary" : "Check Permission for an agent",
        "description" : "This API fetches the license details for an Agent to conduct Remote Session",
        "operationId" : "checkPermission",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/checkPermissionResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.qaautomation.GET" ]
        }, {
          "cookie-auth" : [ "cookie-auth" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 15,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "202517cb8e3e1f140c7790dbad938cbe",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.AssistService.checkPermission"
        }
      }
    },
    "/api/v1/lens/orgInfo" : {
      "get" : {
        "tags" : [ "AssistInteg" ],
        "summary" : "Get Lens Org Info",
        "description" : "This API fetches the org details for Zoho lens",
        "operationId" : "getLensOrgInfo",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/lensOrgInfoJSON"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.settings.READ", "Desk.basic.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "afc1e53d12e44aed3c5a0dec9e0d8fdf",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.AssistService.getLensOrgInfo"
        }
      }
    },
    "/api/v1/lens/licenseInfo" : {
      "get" : {
        "tags" : [ "AssistInteg" ],
        "summary" : "Get Lens License Info",
        "description" : "This API fetches the license details for Zoho lens",
        "operationId" : "getLensLicenseInfo",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/lensLicenseInfoJSON"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.settings.READ", "Desk.basic.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 300000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "c3e63cb68e38205845852ed1e7a6a523",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.AssistService.getLensLicenseInfo"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "curLicenseKeys" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "technician_count" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]+)"
          },
          "pay_cycle" : {
            "type" : [ "string", "null" ],
            "enum" : [ "MONTH", "YEAR", "" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "storage_count" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]*)"
          },
          "days_left" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]*)"
          },
          "license_type" : {
            "type" : [ "string", "null" ],
            "enum" : [ "TRIAL", "FREE", "LICENSED" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "edition" : {
            "type" : [ "string", "null" ],
            "enum" : [ "FREE", "STANDARD", "PROFESSIONAL" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "days_left", "edition", "license_type", "pay_cycle", "storage_count", "technician_count" ]
      },
      "lensOrgParentsKeys" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "service_id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "storage_code" : {
            "type" : [ "string", "null" ],
            "enum" : [ "STORAGE" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "zsoid" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "technician_code" : {
            "type" : [ "string", "null" ],
            "enum" : [ "TECHNICIAN" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "current_license" : {
            "$ref" : "./AssistInteg.json#/components/schemas/curLicenseKeys"
          }
        },
        "required" : [ "current_license", "service_id", "storage_code", "technician_code", "zsoid" ]
      },
      "lensOrgInfoArr" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./AssistInteg.json#/components/schemas/lensOrgParentsKeys"
        }
      },
      "commonAddOnJsonObject" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "monthly_price" : {
            "type" : [ "null", "object" ],
            "additionalProperties" : false
          },
          "store_addon_types" : {
            "type" : [ "string", "null" ],
            "enum" : [ "TECH", "FS", "MSDK" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "store_addon_id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "yearly_price" : {
            "type" : [ "null", "object" ],
            "additionalProperties" : false
          }
        },
        "required" : [ "monthly_price", "store_addon_id", "store_addon_types", "yearly_price" ]
      },
      "msdkAddOnJsonObject" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "store_addon_types" : {
            "type" : [ "string", "null" ],
            "enum" : [ "TECH", "FS", "MSDK" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "store_addon_id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "store_addon_id", "store_addon_types" ]
      },
      "addonsArr" : {
        "type" : [ "null", "array" ],
        "items" : {
          "oneOf" : [ {
            "$ref" : "./AssistInteg.json#/components/schemas/commonAddOnJsonObject"
          }, {
            "$ref" : "./AssistInteg.json#/components/schemas/msdkAddOnJsonObject"
          } ]
        }
      },
      "lensLicInfoKeys" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "store_plan_id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "addons" : {
            "$ref" : "./AssistInteg.json#/components/schemas/addonsArr"
          },
          "edition" : {
            "type" : [ "string", "null" ],
            "enum" : [ "FREE", "STANDARD", "PROFESSIONAL" ],
            "maxLength" : 100,
            "minLength" : 0
          }
        },
        "required" : [ "addons", "edition", "store_plan_id" ]
      },
      "licenseInfoArr" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./AssistInteg.json#/components/schemas/lensLicInfoKeys"
        }
      }
    },
    "responses" : {
      "checkPermissionResponse" : {
        "description" : "checkPermissionResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "oneOf" : [ {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "features" : {
                    "type" : [ "null", "array" ],
                    "items" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    },
                    "uniqueItems" : false
                  },
                  "role" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "Agent", "Admin", "SuperAdmin" ],
                    "maxLength" : 100,
                    "minLength" : 0
                  },
                  "license_type" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "TRIAL", "FREE", "LICENSED" ],
                    "maxLength" : 100,
                    "minLength" : 0
                  }
                },
                "required" : [ "features", "license_type", "role" ]
              }, {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "features" : {
                    "type" : [ "null", "array" ],
                    "items" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    },
                    "uniqueItems" : false
                  },
                  "role" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "Agent", "Admin", "SuperAdmin" ],
                    "maxLength" : 100,
                    "minLength" : 0
                  },
                  "license_type" : {
                    "type" : [ "string", "null" ],
                    "enum" : [ "TRIAL", "FREE", "LICENSED" ],
                    "maxLength" : 100,
                    "minLength" : 0
                  },
                  "daysLeft" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int32",
                    "pattern" : "([0-9]+)"
                  }
                },
                "required" : [ "daysLeft", "features", "license_type", "role" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "licenseType" : "TRIAL",
                  "features" : [ "SCHEDULE_SESSION", "TWO_WAY_SCREEN_SHARING", "REMOTE_SUPPORT" ],
                  "role" : "SuperAdmin",
                  "daysLeft" : "78"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "lensOrgInfoJSON" : {
        "description" : "lensOrgInfoJSON template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "./AssistInteg.json#/components/schemas/lensOrgInfoArr"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "service_id" : "68123456",
                    "storage_code" : "STORAGE",
                    "zsoid" : "67482767",
                    "technician_code" : "TECHNICIAN",
                    "current_license" : {
                      "technician_count" : 10,
                      "storage_count" : 5,
                      "pay_cycle" : "YEAR|MONTH",
                      "days_left" : 15,
                      "license_type" : "TRIAL|LICENSED",
                      "edition" : "PROFESSIONAL"
                    }
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "lensLicenseInfoJSON" : {
        "description" : "lensLicenseInfoJSON template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "editions" : {
                  "$ref" : "./AssistInteg.json#/components/schemas/licenseInfoArr"
                }
              },
              "required" : [ "editions" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "editions" : [ {
                    "store_plan_id" : "820100",
                    "addons" : [ {
                      "store_addon_types" : "MSDK",
                      "store_addon_id" : "820206"
                    } ],
                    "edition" : "FREE"
                  }, {
                    "store_plan_id" : "820101",
                    "addons" : [ {
                      "monthly_price" : {
                        "EUR" : {
                          "slot5" : 13,
                          "slot4" : 14,
                          "slot3" : 15,
                          "slot2" : 16,
                          "slot1" : 17
                        },
                        "GBP" : {
                          "slot5" : 10,
                          "slot4" : 12,
                          "slot3" : 13,
                          "slot2" : 14,
                          "slot1" : 15
                        }
                      },
                      "store_addon_types" : "TECH",
                      "store_addon_id" : "820201",
                      "yearly_price" : {
                        "EUR" : {
                          "slot5" : 132,
                          "slot4" : 144,
                          "slot3" : 150,
                          "slot2" : 156,
                          "slot1" : 168
                        },
                        "GBP" : {
                          "slot5" : 108,
                          "slot4" : 120,
                          "slot3" : 132,
                          "slot2" : 144,
                          "slot1" : 156
                        }
                      }
                    }, {
                      "store_addon_types" : "MSDK",
                      "store_addon_id" : "820206"
                    } ],
                    "edition" : "STANDARD"
                  }, {
                    "store_plan_id" : "820102",
                    "addons" : [ {
                      "monthly_price" : {
                        "EUR" : {
                          "slot5" : 18,
                          "slot4" : 20,
                          "slot3" : 21,
                          "slot2" : 22,
                          "slot1" : 23
                        },
                        "GBP" : {
                          "slot5" : 15,
                          "slot4" : 16,
                          "slot3" : 17,
                          "slot2" : 18,
                          "slot1" : 20
                        }
                      },
                      "store_addon_types" : "TECH",
                      "store_addon_id" : "820202",
                      "yearly_price" : {
                        "EUR" : {
                          "slot5" : 180,
                          "slot4" : 192,
                          "slot3" : 204,
                          "slot2" : 216,
                          "slot1" : 228
                        },
                        "GBP" : {
                          "slot5" : 156,
                          "slot4" : 156,
                          "slot3" : 168,
                          "slot2" : 180,
                          "slot1" : 192
                        }
                      }
                    }, {
                      "monthly_price" : {
                        "EUR" : "0.92",
                        "GBP" : "1"
                      },
                      "store_addon_types" : "FS",
                      "store_addon_id" : "820203",
                      "yearly_price" : {
                        "EUR" : "11",
                        "GBP" : "10.8"
                      }
                    }, {
                      "store_addon_types" : "MSDK",
                      "store_addon_id" : "820206"
                    } ],
                    "edition" : "PROFESSIONAL"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : { },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "jwt-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/jwt-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "AssistInteg"
}