{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "DataImport",
    "version" : "1.0.0",
    "x-clan-group" : "reports",
    "x-module-group" : "import"
  },
  "paths" : {
    "/api/v1/dataImport/{dataImportId}/transformations" : {
      "get" : {
        "tags" : [ "DataImport" ],
        "summary" : "Get Transformations of Data Import",
        "description" : "This API allows to get transformations of a particular data import request",
        "operationId" : "Get Transformations of Data Import",
        "parameters" : [ {
          "$ref" : "#/components/parameters/module"
        }, {
          "$ref" : "#/components/parameters/dataImportId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/DataImportAddActionResponseList"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.imports.CUSTOM" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 120000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "reports",
          "apihash" : "c4600bc6d5969f77588a9bf5432bbd6b",
          "module-group" : "import",
          "apimethod" : "com.zoho.support.restapi.DataImportCustomActionService.getCustomActions"
        }
      },
      "post" : {
        "tags" : [ "DataImport" ],
        "summary" : "Add Transformations to Data Import",
        "description" : "This API allows to add new transformations to a data import request",
        "operationId" : "AddDataImportTransformations",
        "parameters" : [ {
          "$ref" : "#/components/parameters/module"
        }, {
          "$ref" : "#/components/parameters/dataImportId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/DataImportAddCustomActionsTemplate"
        },
        "responses" : {
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/DataImportAddActionResponseList"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.imports.CUSTOM" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 120000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "reports",
          "apihash" : "35cfd6621293ce607d50b3e9fdfdcc0a",
          "module-group" : "import",
          "apimethod" : "com.zoho.support.restapi.DataImportCustomActionService.addCustomActions"
        }
      }
    },
    "/api/v1/dataImport/{dataImportId}/transformations/{transformationId}" : {
      "delete" : {
        "tags" : [ "DataImport" ],
        "summary" : "Delete Data Import  Transformation",
        "description" : "This API deletes a dataImport Transformation that has been added previously",
        "operationId" : "Delete Data Import  Transformation",
        "parameters" : [ {
          "$ref" : "#/components/parameters/dataImportId"
        }, {
          "$ref" : "#/components/parameters/transformationId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "204" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.imports.CUSTOM" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 120000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "reports",
          "apihash" : "fafc0d035b4d7d4295eec7865d18abd8",
          "module-group" : "import",
          "apimethod" : "com.zoho.support.restapi.DataImportCustomActionService.deleteCustomAction"
        }
      },
      "patch" : {
        "tags" : [ "DataImport" ],
        "summary" : "Update Transformation of Data Import",
        "description" : "This API allows to update an already added transformation of a particular data import request",
        "operationId" : "Update Data Import Transformation",
        "parameters" : [ {
          "$ref" : "#/components/parameters/dataImportId"
        }, {
          "$ref" : "#/components/parameters/transformationId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/DataImportAddCustomActionTemplate"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/dataImportAddActionResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.imports.CUSTOM" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 120000,
                  "threshold" : 50,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "reports",
          "apihash" : "6e4aa1ba690e5af665b93328662dc42b",
          "module-group" : "import",
          "apimethod" : "com.zoho.support.restapi.DataImportCustomActionService.updateCustomAction"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "dataImportAddActionResponse" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "columnType" : {
            "type" : [ "string", "null" ],
            "enum" : [ "Boolean", "TinyInt", "Integer", "Long", "Decimal", "Date", "DateTime", "Text", "MediumText", "LargeText" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "Boolean|TinyInt|Integer|Long|Decimal|Date|DateTime|Text|MediumText|LargeText"
          },
          "expression" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "criteria" : {
            "type" : [ "null", "object" ],
            "additionalProperties" : false,
            "maxProperties" : 4,
            "minProperties" : 4,
            "properties" : {
              "criteriaId" : {
                "type" : [ "null", "integer" ],
                "format" : "int64"
              },
              "transformationId" : {
                "type" : [ "null", "integer" ],
                "format" : "int64"
              },
              "pattern" : {
                "type" : [ "string", "null", "integer" ],
                "format" : "int32",
                "pattern" : "([0-9]+)"
              },
              "criterions" : {
                "type" : [ "null", "array" ],
                "items" : {
                  "type" : [ "null", "object" ],
                  "additionalProperties" : false,
                  "maxProperties" : 6,
                  "minProperties" : 6,
                  "properties" : {
                    "comparator" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    },
                    "criterionId" : {
                      "type" : [ "null", "integer" ],
                      "format" : "int64"
                    },
                    "patternOrder" : {
                      "type" : [ "string", "null", "integer" ],
                      "format" : "int32",
                      "pattern" : "([0-9]+)"
                    },
                    "criteriaId" : {
                      "type" : [ "null", "integer" ],
                      "format" : "int64"
                    },
                    "column" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    },
                    "value" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    }
                  },
                  "required" : [ "column", "comparator", "criteriaId", "criterionId", "patternOrder", "value" ]
                },
                "uniqueItems" : false
              }
            },
            "required" : [ "criteriaId", "criterions", "pattern", "transformationId" ]
          },
          "column" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "transformationType" : {
            "type" : [ "string", "null" ],
            "enum" : [ "create", "update", "delete", "relation", "drop" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "create|update|delete|relation|drop"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "moduleId" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "parameters" : {
            "type" : [ "null", "array" ],
            "items" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "maxProperties" : 5,
              "minProperties" : 5,
              "properties" : {
                "transformationId" : {
                  "type" : [ "null", "integer" ],
                  "format" : "int64"
                },
                "variableKey" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "transformationParamId" : {
                  "type" : [ "null", "integer" ],
                  "format" : "int64"
                },
                "type" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "value" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                }
              },
              "required" : [ "transformationId", "transformationParamId", "type", "value", "variableKey" ]
            },
            "uniqueItems" : false
          },
          "order" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int32",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "column", "columnType", "criteria", "expression", "id", "moduleId", "name", "order", "parameters", "transformationType" ]
      },
      "DataImportAddCustomActionTemplate" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "columnType" : {
            "type" : [ "string", "null" ],
            "enum" : [ "Boolean", "TinyInt", "Integer", "Long", "Decimal", "Date", "DateTime", "Text", "MediumText", "LargeText" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "Boolean|TinyInt|Integer|Long|Decimal|Date|DateTime|Text|MediumText|LargeText"
          },
          "expression" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "criteria" : {
            "type" : [ "null", "object" ],
            "additionalProperties" : false,
            "maxProperties" : 2,
            "minProperties" : 2,
            "properties" : {
              "pattern" : {
                "type" : [ "string", "null" ],
                "maxLength" : 100,
                "minLength" : 0
              },
              "criterions" : {
                "type" : [ "null", "array" ],
                "items" : {
                  "type" : [ "null", "object" ],
                  "additionalProperties" : false,
                  "maxProperties" : 4,
                  "minProperties" : 4,
                  "properties" : {
                    "comparator" : {
                      "type" : [ "string", "null" ],
                      "enum" : [ "equal", "not_equal", "greater_equal", "greater_than", "less_equal", "less_than", "in", "not_in", "starts_with", "ends_with", "contains", "not_contains", "between", "not_between", "is_null", "is_not_null" ],
                      "maxLength" : 100,
                      "minLength" : 0,
                      "pattern" : "equal|not_equal|greater_equal|greater_than|less_equal|less_than|in|not_in|starts_with|ends_with|contains|not_contains|between|not_between|is_null|is_not_null"
                    },
                    "patternOrder" : {
                      "type" : [ "string", "null", "integer" ],
                      "format" : "int32",
                      "pattern" : "([0-9]+)"
                    },
                    "column" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    },
                    "value" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    }
                  },
                  "required" : [ "column", "comparator", "patternOrder", "value" ]
                },
                "uniqueItems" : false
              }
            },
            "required" : [ "criterions", "pattern" ]
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "column" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "transformationType" : {
            "type" : [ "string", "null" ],
            "enum" : [ "create", "update", "delete", "relation", "drop" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "create|update|delete|relation|drop"
          },
          "parameters" : {
            "type" : [ "null", "array" ],
            "items" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "maxProperties" : 3,
              "minProperties" : 3,
              "properties" : {
                "valueType" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "column", "value", "expr", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "column|value|expr|null"
                },
                "variableKey" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "value" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                }
              },
              "required" : [ "value", "valueType", "variableKey" ]
            },
            "uniqueItems" : false
          }
        },
        "required" : [ "column", "columnType", "criteria", "expression", "name", "parameters", "transformationType" ]
      },
      "DataImportAddCustomActionsArray" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./DataImport.json#/components/schemas/DataImportAddCustomActionTemplate"
        }
      }
    },
    "responses" : {
      "DataImportAddActionResponseList" : {
        "description" : "DataImportAddActionResponseList template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "array" ],
              "items" : {
                "$ref" : "./DataImport.json#/components/schemas/dataImportAddActionResponse"
              }
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "columnType" : "TEXT",
                    "expressionParameters" : [ {
                      "variableKey" : "$1",
                      "type" : "VALUE",
                      "value" : "noname"
                    } ],
                    "expression" : "set($1)",
                    "criteria" : {
                      "pattern" : "1",
                      "criterions" : [ {
                        "comparator" : "IS_NULL",
                        "column" : "lastName",
                        "criterionOrder" : "1",
                        "value" : ""
                      } ]
                    },
                    "column" : "lastName",
                    "name" : "lastName2",
                    "transformationType" : "UPDATE",
                    "id" : "4000000139003"
                  }, {
                    "columnType" : "TEXT",
                    "expressionParameters" : [ {
                      "variableKey" : "$1",
                      "type" : "VALUE",
                      "value" : "noname"
                    } ],
                    "expression" : "set($1)",
                    "criteria" : {
                      "pattern" : "1",
                      "criterions" : [ {
                        "comparator" : "IS_NULL",
                        "column" : "lastName",
                        "criterionOrder" : "1",
                        "value" : ""
                      } ]
                    },
                    "column" : "lastName",
                    "name" : "lastName",
                    "transformationType" : "UPDATE",
                    "id" : "4000000148003"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "dataImportAddActionResponse" : {
        "description" : "dataImportAddActionResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "columnType" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "Boolean", "TinyInt", "Integer", "Long", "Decimal", "Date", "DateTime", "Text", "MediumText", "LargeText" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "Boolean|TinyInt|Integer|Long|Decimal|Date|DateTime|Text|MediumText|LargeText",
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "replacementString" : "",
                    "allowInvalid" : false,
                    "descrption" : "Column type. Allowed values are @BOOLEAN@, @TINYINT@, @INTEGER@, @LONG@, @DECIMAL@, @DATE@, @DATETIME@, @TEXT@, @MEDIUMTEXT@, @LARGETEXT@",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "expression" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "replacementString" : "",
                    "allowInvalid" : false,
                    "descrption" : "Function expression to perform transformation",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "criteria" : {
                  "type" : [ "null", "object" ],
                  "additionalProperties" : false,
                  "maxProperties" : 4,
                  "minProperties" : 4,
                  "properties" : {
                    "criteriaId" : {
                      "type" : [ "null", "integer" ],
                      "format" : "int64"
                    },
                    "transformationId" : {
                      "type" : [ "null", "integer" ],
                      "format" : "int64"
                    },
                    "pattern" : {
                      "type" : [ "string", "null", "integer" ],
                      "format" : "int32",
                      "pattern" : "([0-9]+)"
                    },
                    "criterions" : {
                      "type" : [ "null", "array" ],
                      "items" : {
                        "type" : [ "null", "object" ],
                        "additionalProperties" : false,
                        "maxProperties" : 6,
                        "minProperties" : 6,
                        "properties" : {
                          "comparator" : {
                            "type" : [ "string", "null" ],
                            "maxLength" : 100,
                            "minLength" : 0
                          },
                          "criterionId" : {
                            "type" : [ "null", "integer" ],
                            "format" : "int64"
                          },
                          "patternOrder" : {
                            "type" : [ "string", "null", "integer" ],
                            "format" : "int32",
                            "pattern" : "([0-9]+)"
                          },
                          "criteriaId" : {
                            "type" : [ "null", "integer" ],
                            "format" : "int64"
                          },
                          "column" : {
                            "type" : [ "string", "null" ],
                            "maxLength" : 100,
                            "minLength" : 0
                          },
                          "value" : {
                            "type" : [ "string", "null" ],
                            "maxLength" : 100,
                            "minLength" : 0
                          }
                        },
                        "required" : [ "column", "comparator", "criteriaId", "criterionId", "patternOrder", "value" ]
                      },
                      "uniqueItems" : false
                    }
                  },
                  "required" : [ "criteriaId", "criterions", "pattern", "transformationId" ]
                },
                "column" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "replacementString" : "",
                    "allowInvalid" : false,
                    "descrption" : "Column for which the transformation is to be performed",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "replacementString" : "",
                    "allowInvalid" : false,
                    "descrption" : "Name of the transformation",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "transformationType" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "create", "update", "delete", "relation", "drop" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "create|update|delete|relation|drop",
                  "x-custom-parameters-attributes" : {
                    "removeExif" : false,
                    "filterMatchedContent" : false,
                    "antivirus" : false,
                    "replacementString" : "",
                    "allowInvalid" : false,
                    "descrption" : "Type of transformation. Allowed values are @CREATE@, @UPDATE@, @DELETE@, @RELATION@, @DELETE_RECORDS@",
                    "secret" : false,
                    "preserveCharsLimit" : 10,
                    "trim" : false,
                    "internalParam" : false,
                    "preserveChars" : "0,5",
                    "importUrl" : false,
                    "decrypt" : false
                  }
                },
                "id" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "pattern" : "([0-9]+)"
                },
                "moduleId" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "pattern" : "([0-9]+)"
                },
                "parameters" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "null", "object" ],
                    "additionalProperties" : false,
                    "maxProperties" : 5,
                    "minProperties" : 5,
                    "properties" : {
                      "transformationId" : {
                        "type" : [ "null", "integer" ],
                        "format" : "int64"
                      },
                      "variableKey" : {
                        "type" : [ "string", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0
                      },
                      "transformationParamId" : {
                        "type" : [ "null", "integer" ],
                        "format" : "int64"
                      },
                      "type" : {
                        "type" : [ "string", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0
                      },
                      "value" : {
                        "type" : [ "string", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0
                      }
                    },
                    "required" : [ "transformationId", "transformationParamId", "type", "value", "variableKey" ]
                  },
                  "uniqueItems" : false
                },
                "order" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int32",
                  "pattern" : "([0-9]+)"
                }
              },
              "required" : [ "column", "columnType", "criteria", "expression", "id", "moduleId", "name", "order", "parameters", "transformationType" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : {
                    "columnType" : "TEXT",
                    "expressionParameters" : [ {
                      "variableKey" : "$1",
                      "type" : "VALUE",
                      "value" : "noname2"
                    } ],
                    "expression" : "set($1)",
                    "criteria" : {
                      "pattern" : "1",
                      "criterions" : [ {
                        "comparator" : "IS_NULL",
                        "column" : "lastName",
                        "criterionOrder" : "1",
                        "value" : "ABC"
                      } ]
                    },
                    "column" : "lastName6",
                    "name" : "lastName9",
                    "transformationType" : "CREATE",
                    "id" : "3263000000074591"
                  }
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : {
      "dataImportId" : {
        "name" : "dataImportId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      },
      "module" : {
        "name" : "module",
        "in" : "query",
        "description" : "Api Name of the module for which custom Actions are to be added.",
        "required" : false,
        "style" : "form",
        "explode" : true,
        "schema" : {
          "type" : [ "string", "null" ],
          "description" : "Api Name of the module for which custom Actions are to be added.",
          "maxLength" : 100,
          "minLength" : 0
        }
      },
      "transformationId" : {
        "name" : "transformationId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      }
    },
    "requestBodies" : {
      "DataImportAddCustomActionsTemplate" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "transformationsList" : {
                  "$ref" : "./DataImport.json#/components/schemas/DataImportAddCustomActionsArray"
                }
              },
              "required" : [ "transformationsList" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "transformationsList" : [ {
                    "columnType" : "TEXT",
                    "expressionParameters" : [ {
                      "valueType" : "VALUE",
                      "variableKey" : "$1",
                      "value" : "noname"
                    } ],
                    "expression" : "set($1)",
                    "criteria" : {
                      "pattern" : "1",
                      "criterions" : [ {
                        "comparator" : "IS_NULL",
                        "column" : "lastName",
                        "criterionOrder" : "1",
                        "value" : ""
                      } ]
                    },
                    "name" : "lastName",
                    "column" : "lastName",
                    "transformationType" : "UPDATE"
                  }, {
                    "columnType" : "TEXT",
                    "expressionParameters" : [ {
                      "valueType" : "VALUE",
                      "variableKey" : "$1",
                      "value" : "noname"
                    } ],
                    "expression" : "set($1)",
                    "criteria" : {
                      "pattern" : "1",
                      "criterions" : [ {
                        "comparator" : "IS_NULL",
                        "column" : "lastName",
                        "criterionOrder" : "1",
                        "value" : ""
                      } ]
                    },
                    "name" : "lastName2",
                    "column" : "lastName",
                    "transformationType" : "UPDATE"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "DataImportAddCustomActionTemplate" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "columnType" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "Boolean", "TinyInt", "Integer", "Long", "Decimal", "Date", "DateTime", "Text", "MediumText", "LargeText" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "Boolean|TinyInt|Integer|Long|Decimal|Date|DateTime|Text|MediumText|LargeText"
                },
                "expression" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "criteria" : {
                  "type" : [ "null", "object" ],
                  "additionalProperties" : false,
                  "maxProperties" : 2,
                  "minProperties" : 2,
                  "properties" : {
                    "pattern" : {
                      "type" : [ "string", "null" ],
                      "maxLength" : 100,
                      "minLength" : 0
                    },
                    "criterions" : {
                      "type" : [ "null", "array" ],
                      "items" : {
                        "type" : [ "null", "object" ],
                        "additionalProperties" : false,
                        "maxProperties" : 4,
                        "minProperties" : 4,
                        "properties" : {
                          "comparator" : {
                            "type" : [ "string", "null" ],
                            "enum" : [ "equal", "not_equal", "greater_equal", "greater_than", "less_equal", "less_than", "in", "not_in", "starts_with", "ends_with", "contains", "not_contains", "between", "not_between", "is_null", "is_not_null" ],
                            "maxLength" : 100,
                            "minLength" : 0,
                            "pattern" : "equal|not_equal|greater_equal|greater_than|less_equal|less_than|in|not_in|starts_with|ends_with|contains|not_contains|between|not_between|is_null|is_not_null"
                          },
                          "patternOrder" : {
                            "type" : [ "string", "null", "integer" ],
                            "format" : "int32",
                            "pattern" : "([0-9]+)"
                          },
                          "column" : {
                            "type" : [ "string", "null" ],
                            "maxLength" : 100,
                            "minLength" : 0
                          },
                          "value" : {
                            "type" : [ "string", "null" ],
                            "maxLength" : 100,
                            "minLength" : 0
                          }
                        },
                        "required" : [ "column", "comparator", "patternOrder", "value" ]
                      },
                      "uniqueItems" : false
                    }
                  },
                  "required" : [ "criterions", "pattern" ]
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "column" : {
                  "type" : [ "string", "null" ],
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "transformationType" : {
                  "type" : [ "string", "null" ],
                  "enum" : [ "create", "update", "delete", "relation", "drop" ],
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "create|update|delete|relation|drop"
                },
                "parameters" : {
                  "type" : [ "null", "array" ],
                  "items" : {
                    "type" : [ "null", "object" ],
                    "additionalProperties" : false,
                    "maxProperties" : 3,
                    "minProperties" : 3,
                    "properties" : {
                      "valueType" : {
                        "type" : [ "string", "null" ],
                        "enum" : [ "column", "value", "expr", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "column|value|expr|null"
                      },
                      "variableKey" : {
                        "type" : [ "string", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0
                      },
                      "value" : {
                        "type" : [ "string", "null" ],
                        "maxLength" : 100,
                        "minLength" : 0
                      }
                    },
                    "required" : [ "value", "valueType", "variableKey" ]
                  },
                  "uniqueItems" : false
                }
              }
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "columnType" : "TEXT",
                  "expressionParameters" : [ {
                    "valueType" : "VALUE",
                    "variableKey" : "$1",
                    "value" : "noname2"
                  } ],
                  "expression" : "set($1)",
                  "criteria" : {
                    "pattern" : "1",
                    "criterions" : [ {
                      "comparator" : "IS_NULL",
                      "column" : "lastName",
                      "criterionOrder" : "1",
                      "value" : "ABC"
                    } ]
                  },
                  "name" : "lastName9",
                  "column" : "lastName6",
                  "transformationType" : "CREATE"
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "DataImport"
}