{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "PBGroup",
    "version" : "1.0.0",
    "x-clan-group" : "secModule",
    "x-module-group" : "telephony"
  },
  "paths" : {
    "/api/v1/pbx/{pbxName}/phoneBridgeGroup/{groupId}" : {
      "get" : {
        "tags" : [ "PBGroup" ],
        "summary" : "Get PhoneBridge Group",
        "description" : "This API fetches the specified PhoneBridge Group created in your Zoho Desk portal.",
        "operationId" : "getPBGroup",
        "parameters" : [ {
          "$ref" : "#/components/parameters/pbxName"
        }, {
          "$ref" : "#/components/parameters/groupId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/pbGroupJson"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "secModule",
          "apihash" : "d9b44cc71cffa22a29ef2ea25893944b",
          "module-group" : "telephony",
          "apimethod" : "com.zoho.desk.telephony.config.PBGroup.PBGroupService.getPBGroup"
        }
      },
      "patch" : {
        "tags" : [ "PBGroup" ],
        "summary" : "Update PhoneBridge Group",
        "description" : "This API updates a PhoneBridge Group in your Zoho Desk portal.",
        "operationId" : "updatePBGroup",
        "parameters" : [ {
          "$ref" : "#/components/parameters/pbxName"
        }, {
          "$ref" : "#/components/parameters/groupId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updatePBGroup_pbGroupJsonPayLoad"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/pbGroupJson"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 10,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "secModule",
          "apihash" : "859a8b757cb4d90101bbc6b79daff14d",
          "module-group" : "telephony",
          "apimethod" : "com.zoho.desk.telephony.config.PBGroup.PBGroupService.updatePBGroup"
        }
      }
    },
    "/api/v1/pbx/{pbxName}/phoneBridgeGroup" : {
      "get" : {
        "tags" : [ "PBGroup" ],
        "summary" : "List PhoneBridge Group",
        "description" : "This API lists all the PhoneBridge Group created in your Zoho Desk portal.",
        "operationId" : "getPBGroupList",
        "parameters" : [ {
          "$ref" : "#/components/parameters/pbxName"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "200" : {
            "$ref" : "#/components/responses/getListOfPbGroupJson"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 20,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "secModule",
          "apihash" : "c8e4025e8506caa614f4574425a4e357",
          "module-group" : "telephony",
          "apimethod" : "com.zoho.desk.telephony.config.PBGroup.PBGroupService.getPBGroupList"
        }
      },
      "post" : {
        "tags" : [ "PBGroup" ],
        "summary" : "Add PhoneBridge Group",
        "description" : "This API adds a PhoneBridge Group in your Zoho Desk portal.",
        "operationId" : "addPBGroup",
        "parameters" : [ {
          "$ref" : "#/components/parameters/pbxName"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/pbGroupJsonPayLoad"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/pbGroupJson"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "403" : {
            "$ref" : "../common/Common.json#/components/responses/forbiddenErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.settings.CREATE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 600000,
                  "threshold" : 10,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "secModule",
          "apihash" : "ad4b5cd5a2ed29abc6bf2b031084353a",
          "module-group" : "telephony",
          "apimethod" : "com.zoho.desk.telephony.config.PBGroup.PBGroupService.addPBGroup"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "agentsJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "extension" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "([a-zA-Z0-9():.; ])+"
          },
          "isDefaultExtension" : {
            "type" : [ "boolean", "null" ]
          },
          "defaultDialCode" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "[A-Za-z0-9~@$%_\\!\\^\\[\\]\\{\\},#*:`.'\" & \\+\\ ? \\-\\/\\|\\P{InBasicLatin}\\s]+"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "defaultDialCode", "extension", "id", "isDefaultExtension" ]
      },
      "agentslist" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./PBGroup.json#/components/schemas/agentsJson"
        }
      },
      "allPbGroupJson" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "groupIdentifyMemberId" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "pbxDialCode" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "([a-zA-Z0-9():.; ])+"
          },
          "name" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          }
        },
        "required" : [ "groupIdentifyMemberId", "id", "name", "pbxDialCode" ]
      },
      "listOfPbGroupJson" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./PBGroup.json#/components/schemas/allPbGroupJson"
        }
      }
    },
    "responses" : {
      "pbGroupJson" : {
        "description" : "pbGroupJson template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "additionalProperties" : false,
              "allOf" : [ {
                "$ref" : "./PBGroup.json#/components/schemas/allPbGroupJson"
              }, {
                "type" : [ "null", "object" ],
                "properties" : {
                  "agents" : {
                    "$ref" : "./PBGroup.json#/components/schemas/agentslist"
                  }
                },
                "required" : [ "agents" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "groupIdentifyMemberId" : "6408821",
                  "pbxDialCode" : "ISD:100",
                  "name" : "Billing Support",
                  "id" : "5000000019029",
                  "agents" : [ {
                    "extension" : "205",
                    "isDefaultExtension" : false,
                    "defaultDialCode" : "NOPREFIX",
                    "id" : "5000000015887"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "getListOfPbGroupJson" : {
        "description" : "getListOfPbGroupJson template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "data" : {
                  "$ref" : "./PBGroup.json#/components/schemas/listOfPbGroupJson"
                }
              },
              "required" : [ "data" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "data" : [ {
                    "groupIdentifyMemberId" : "6401113",
                    "pbxDialCode" : "ISD:100",
                    "name" : "Marketing Support",
                    "id" : "5000000017023"
                  }, {
                    "groupIdentifyMemberId" : "6408821",
                    "pbxDialCode" : "",
                    "name" : "Sales Support",
                    "id" : "5000000019029"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : {
      "pbxName" : {
        "name" : "pbxName",
        "in" : "path",
        "description" : "",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null" ],
          "description" : "",
          "maxLength" : 100,
          "minLength" : 0,
          "pattern" : "([a-zA-Z0-9.\\-\\s]+)"
        }
      },
      "groupId" : {
        "name" : "groupId",
        "in" : "path",
        "description" : "",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "description" : "",
          "pattern" : "([0-9]+)"
        }
      }
    },
    "requestBodies" : {
      "pbGroupJsonPayLoad" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "groupIdentifyMemberId" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "description" : "",
                  "pattern" : "([0-9]+)"
                },
                "pbxDialCode" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "([a-zA-Z0-9():.; ])+"
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "agents" : {
                  "type" : [ "null", "array" ],
                  "description" : "",
                  "items" : {
                    "type" : [ "null", "object" ],
                    "additionalProperties" : false,
                    "description" : "",
                    "maxProperties" : 4,
                    "minProperties" : 4,
                    "properties" : {
                      "extension" : {
                        "type" : [ "string", "null" ],
                        "description" : "",
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "([a-zA-Z0-9():.; ])+",
                        "x-custom-parameters-attributes" : [ ]
                      },
                      "isDefaultExtension" : {
                        "type" : [ "boolean", "null" ],
                        "description" : "",
                        "x-custom-parameters-attributes" : [ ]
                      },
                      "defaultDialCode" : {
                        "type" : [ "string", "null" ],
                        "description" : "",
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "[A-Za-z0-9~@$%_\\!\\^\\[\\]\\{\\},#*:`.'\" & \\+\\ ? \\-\\/\\|\\P{InBasicLatin}\\s]+",
                        "x-custom-parameters-attributes" : [ ]
                      },
                      "id" : {
                        "type" : [ "string", "null", "integer" ],
                        "format" : "int64",
                        "description" : "",
                        "pattern" : "([0-9]+)",
                        "x-custom-parameters-attributes" : [ ]
                      }
                    },
                    "required" : [ "defaultDialCode", "extension", "id", "isDefaultExtension" ],
                    "x-custom-parameters-attributes" : [ ]
                  },
                  "uniqueItems" : false
                }
              },
              "required" : [ "agents", "groupIdentifyMemberId", "name" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "groupIdentifyMemberId" : "6401113",
                  "pbxDialCode" : "ISD:100",
                  "name" : "Marketing Support",
                  "agents" : [ {
                    "extension" : "101",
                    "isDefaultExtension" : false,
                    "defaultDialCode" : "",
                    "id" : "5000000015887"
                  }, {
                    "extension" : "102",
                    "isDefaultExtension" : false,
                    "defaultDialCode" : "",
                    "id" : "5000000018001"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "updatePBGroup_pbGroupJsonPayLoad" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "groupIdentifyMemberId" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "description" : "",
                  "pattern" : "([0-9]+)"
                },
                "pbxDialCode" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 100,
                  "minLength" : 0,
                  "pattern" : "([a-zA-Z0-9():.; ])+"
                },
                "name" : {
                  "type" : [ "string", "null" ],
                  "description" : "",
                  "maxLength" : 100,
                  "minLength" : 0
                },
                "agents" : {
                  "type" : [ "null", "array" ],
                  "description" : "",
                  "items" : {
                    "type" : [ "null", "object" ],
                    "additionalProperties" : false,
                    "description" : "",
                    "maxProperties" : 4,
                    "minProperties" : 4,
                    "properties" : {
                      "extension" : {
                        "type" : [ "string", "null" ],
                        "description" : "",
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "([a-zA-Z0-9():.; ])+",
                        "x-custom-parameters-attributes" : [ ]
                      },
                      "isDefaultExtension" : {
                        "type" : [ "boolean", "null" ],
                        "description" : "",
                        "x-custom-parameters-attributes" : [ ]
                      },
                      "defaultDialCode" : {
                        "type" : [ "string", "null" ],
                        "description" : "",
                        "maxLength" : 100,
                        "minLength" : 0,
                        "pattern" : "[A-Za-z0-9~@$%_\\!\\^\\[\\]\\{\\},#*:`.'\" & \\+\\ ? \\-\\/\\|\\P{InBasicLatin}\\s]+",
                        "x-custom-parameters-attributes" : [ ]
                      },
                      "id" : {
                        "type" : [ "string", "null", "integer" ],
                        "format" : "int64",
                        "description" : "",
                        "pattern" : "([0-9]+)",
                        "x-custom-parameters-attributes" : [ ]
                      }
                    },
                    "required" : [ "defaultDialCode", "extension", "id", "isDefaultExtension" ],
                    "x-custom-parameters-attributes" : [ ]
                  },
                  "uniqueItems" : false
                }
              },
              "required" : [ "agents", "groupIdentifyMemberId", "name" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "agents" : [ {
                    "extension" : "205",
                    "isDefaultExtension" : false,
                    "defaultDialCode" : "NOPREFIX",
                    "id" : "5000000015887"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "PBGroup"
}