{
  "openapi" : "3.1.0",
  "info" : {
    "title" : "Slack",
    "version" : "1.0.0",
    "x-clan-group" : "integration",
    "x-module-group" : "integration"
  },
  "paths" : {
    "/api/v1/slackTeams/{integId}" : {
      "get" : {
        "tags" : [ "Slack" ],
        "summary" : "Slack Team Detail",
        "description" : "To get the Slack Team detail of the given Desk portal for the given teamId",
        "operationId" : "getTeamIntegrationDetails",
        "parameters" : [ {
          "$ref" : "#/components/parameters/integId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getTeamIntegrationDetailsResponse"
          },
          "401" : {
            "$ref" : "../common/Common.json#/components/responses/unauthorizedErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.integrations.READ", "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 20,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "7a18e64febb6e3227d81ff0ee6f5fc00",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.SlackService.slackTeamInfo"
        }
      },
      "delete" : {
        "tags" : [ "Slack" ],
        "summary" : "Delete Slack Team Details",
        "description" : "To delete the Slack Team details of the given Desk portal",
        "operationId" : "deleteSlackTeam",
        "parameters" : [ {
          "$ref" : "#/components/parameters/integId"
        }, {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "401" : {
            "$ref" : "../common/Common.json#/components/responses/unauthorizedErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "200" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.integrations.DELETE", "Desk.settings.DELETE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 10,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "63cf1e42de3683b2e2bb16e272496b4c",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.SlackService.deleteSlackTeam"
        }
      }
    },
    "/api/v1/slackTeams" : {
      "get" : {
        "tags" : [ "Slack" ],
        "summary" : "Slack Team Details",
        "description" : "To get the Slack Team details of the given Desk portal",
        "operationId" : "getIntegratedSlackTeams",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/getIntegratedSlackTeamsResponse"
          },
          "401" : {
            "$ref" : "../common/Common.json#/components/responses/unauthorizedErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.integrations.READ", "Desk.settings.READ" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 20,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "14bb89d19ec334fcf8aabc36f7be59b9",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.SlackService.slackTeam"
        }
      },
      "delete" : {
        "tags" : [ "Slack" ],
        "summary" : "Delete Slack Integration",
        "description" : "To delete the Slack Integration for the given Desk portal",
        "operationId" : "deleteSlackIntegration",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "responses" : {
          "401" : {
            "$ref" : "../common/Common.json#/components/responses/unauthorizedErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          },
          "200" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.integrations.DELETE", "Desk.settings.DELETE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 10,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "27f1a3b1d4c34e8c2ec05b729cace059",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.SlackService.deleteSlackInteg"
        }
      },
      "patch" : {
        "tags" : [ "Slack" ],
        "summary" : "Update Slack Team Detail",
        "description" : "To update the Slack Team detail of the given Desk portal for the given teamId",
        "operationId" : "updateTeamIntegrationDetails",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateTeamIntegrationRequestBody"
        },
        "responses" : {
          "200" : {
            "$ref" : "#/components/responses/updateTeamIntegrationDetailsResponse"
          },
          "401" : {
            "$ref" : "../common/Common.json#/components/responses/unauthorizedErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.integrations.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 30,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "a9cb7f4760e89b684d779d8a3452dcd1",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.SlackService.slackTeamUpdate"
        }
      }
    },
    "/api/v1/slack" : {
      "patch" : {
        "tags" : [ "Slack" ],
        "summary" : "Update Slack Integ Detail",
        "description" : "To update the Slack Integ detail for the given Desk portal",
        "operationId" : "updateSlackTeamIntegrationStatus",
        "parameters" : [ {
          "$ref" : "../common/Common.json#/components/parameters/orgId"
        } ],
        "requestBody" : {
          "$ref" : "#/components/requestBodies/updateSlackTeamIntegrationStatusJsonRequestBody"
        },
        "responses" : {
          "200" : {
            "$ref" : "../common/Common.json#/components/responses/emptyResponse"
          },
          "422" : {
            "$ref" : "../common/Common.json#/components/responses/multipleUnprocessEntityResponse"
          },
          "401" : {
            "$ref" : "../common/Common.json#/components/responses/unauthorizedErrorResponse"
          },
          "500" : {
            "$ref" : "../common/Common.json#/components/responses/internalErrorResponse"
          }
        },
        "security" : [ {
          "org-oauth" : [ "Desk.accessAll.ALL" ]
        }, {
          "iam-oauth2-schema" : [ "Desk.integrations.UPDATE", "Desk.settings.UPDATE" ]
        } ],
        "x-audience" : [ "company-internal" ],
        "x-custom-url-attribute" : {
          "security" : {
            "throttle" : {
              "inline" : [ {
                "scope" : "APPSERVER",
                "rules" : [ {
                  "duration" : 60000,
                  "lock-period" : 180000,
                  "threshold" : 10,
                  "hip" : false
                } ],
                "window" : "ROLLING",
                "key" : "url.path+user.zuid"
              } ]
            },
            "extraparams" : {
              "disable" : true,
              "ignore" : false
            },
            "authentication" : { }
          },
          "clan-group" : "integration",
          "apihash" : "32373ba3780a3c5d65c51f3dd6e3a0df",
          "module-group" : "integration",
          "apimethod" : "com.zoho.support.restapi.SlackService.slackUpdate"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "mappedChannelsResponse" : {
        "type" : [ "null", "array" ],
        "items" : {
          "type" : [ "null", "object" ],
          "additionalProperties" : false
        }
      },
      "departmentChannelMappingArray" : {
        "type" : [ "null", "array" ],
        "items" : {
          "type" : [ "null", "object" ],
          "additionalProperties" : false,
          "maxProperties" : 3,
          "minProperties" : 3,
          "properties" : {
            "departmentId" : {
              "type" : [ "string", "null", "integer" ],
              "format" : "int64",
              "pattern" : "([0-9]+)"
            },
            "isEnabled" : {
              "type" : [ "boolean", "null" ]
            },
            "channel" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false
            }
          },
          "required" : [ "channel", "departmentId", "isEnabled" ]
        }
      },
      "teamIntegrationDetailResponse" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "teamName" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "isDepartmentChannelMapEnabled" : {
            "type" : [ "boolean", "null" ]
          },
          "slackChannels" : {
            "$ref" : "./Slack.json#/components/schemas/mappedChannelsResponse"
          },
          "displayName" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "notifyOn" : {
            "type" : [ "null", "object" ],
            "additionalProperties" : false,
            "maxProperties" : 10,
            "minProperties" : 10,
            "properties" : {
              "ticketClose" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketBP" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketMove" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketComment" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketStatus" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketRating" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketEscalation" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketCreate" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketAssignee" : {
                "type" : [ "boolean", "null" ]
              },
              "ticketReopen" : {
                "type" : [ "boolean", "null" ]
              }
            },
            "required" : [ "ticketAssignee", "ticketBP", "ticketClose", "ticketComment", "ticketCreate", "ticketEscalation", "ticketMove", "ticketRating", "ticketReopen", "ticketStatus" ]
          },
          "isEnabled" : {
            "type" : [ "boolean", "null" ]
          },
          "logo" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "departmentChannelMapping" : {
            "$ref" : "./Slack.json#/components/schemas/departmentChannelMappingArray"
          },
          "defaultChannel" : {
            "type" : [ "null", "object" ],
            "additionalProperties" : false
          }
        },
        "required" : [ "defaultChannel", "departmentChannelMapping", "displayName", "id", "isDepartmentChannelMapEnabled", "isEnabled", "logo", "notifyOn", "slackChannels", "teamName" ]
      },
      "integratedTeamsResponse" : {
        "type" : [ "null", "object" ],
        "additionalProperties" : false,
        "properties" : {
          "teamName" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "displayName" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0
          },
          "isEnabled" : {
            "type" : [ "boolean", "null" ]
          },
          "logo" : {
            "type" : [ "string", "null" ],
            "maxLength" : 100,
            "minLength" : 0,
            "pattern" : "(^(ht|f)tp(s?)\\://[-.\\w]*(/?)([a-zA-Z0-9\\-\\.\\?\\,\\:\\'/\\\\+=&amp;%\\$#_@]*)?$)"
          },
          "id" : {
            "type" : [ "string", "null", "integer" ],
            "format" : "int64",
            "pattern" : "([0-9]+)"
          },
          "mappedChannels" : {
            "$ref" : "./Slack.json#/components/schemas/mappedChannelsResponse"
          }
        },
        "required" : [ "displayName", "id", "isEnabled", "logo", "mappedChannels", "teamName" ]
      },
      "integratedSlackTeamsResponse" : {
        "type" : [ "null", "array" ],
        "items" : {
          "$ref" : "./Slack.json#/components/schemas/integratedTeamsResponse"
        }
      }
    },
    "responses" : {
      "getTeamIntegrationDetailsResponse" : {
        "description" : "getTeamIntegrationDetailsResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "integDetail" : {
                  "$ref" : "./Slack.json#/components/schemas/teamIntegrationDetailResponse"
                }
              },
              "required" : [ "integDetail" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "teamName" : "helpdeskcorp.slack.com",
                  "mappedchannels" : [ "#champ", "#desk", "#Crm" ],
                  "defaultchannel" : "#champ",
                  "displayName" : "Help Desk Corp",
                  "notifyOn" : {
                    "ticketClose" : true,
                    "ticketCreate" : true,
                    "ticketAssignee" : false
                  },
                  "isEnabled" : true,
                  "logo" : "https://slack.com/team1",
                  "slackchannels" : [ "#champ", "#facebook", "#incoming", "#outgoing", "#zsdesk", "#supportnotify" ],
                  "id" : "1000000021010",
                  "departmentChannelMapping" : [ {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : true,
                    "channel" : "#champ"
                  }, {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : true,
                    "channel" : "#zohocrm"
                  }, {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : false,
                    "channel" : "#proj"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "getIntegratedSlackTeamsResponse" : {
        "description" : "getIntegratedSlackTeamsResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "integDetail" : {
                  "$ref" : "./Slack.json#/components/schemas/integratedSlackTeamsResponse"
                },
                "isEnabled" : {
                  "type" : [ "boolean", "null" ]
                }
              },
              "required" : [ "integDetail", "isEnabled" ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "teamName" : "helpdeskcorp.slack.com",
                  "mappedchannels" : [ "#champ", "#desk", "#Crm" ],
                  "displayName" : "Help Desk Corp",
                  "isEnabled" : true,
                  "logo" : "https://slack.com/team1",
                  "id" : "1000000021010"
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      },
      "updateTeamIntegrationDetailsResponse" : {
        "description" : "updateTeamIntegrationDetailsResponse template definitions",
        "content" : {
          "application/json" : {
            "schema" : {
              "oneOf" : [ {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "isEnabled" : {
                    "type" : [ "boolean", "null" ],
                    "x-custom-parameters-attributes" : {
                      "removeExif" : false,
                      "filterMatchedContent" : false,
                      "antivirus" : false,
                      "replacementString" : "",
                      "allowInvalid" : false,
                      "descrption" : "Slack Integ Status",
                      "secret" : false,
                      "preserveCharsLimit" : 10,
                      "trim" : false,
                      "internalParam" : false,
                      "preserveChars" : "0,5",
                      "importUrl" : false,
                      "decrypt" : false
                    }
                  },
                  "integDetail" : {
                    "$ref" : "./Slack.json#/components/schemas/teamIntegrationDetailResponse"
                  },
                  "integId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : {
                      "removeExif" : false,
                      "filterMatchedContent" : false,
                      "antivirus" : false,
                      "replacementString" : "",
                      "allowInvalid" : false,
                      "descrption" : "Slack Integ Id",
                      "secret" : false,
                      "preserveCharsLimit" : 10,
                      "trim" : false,
                      "internalParam" : false,
                      "preserveChars" : "0,5",
                      "importUrl" : false,
                      "decrypt" : false
                    }
                  }
                },
                "required" : [ "integDetail", "integId", "isEnabled" ]
              }, {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "integDetail" : {
                    "$ref" : "./Slack.json#/components/schemas/teamIntegrationDetailResponse"
                  },
                  "integId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : {
                      "removeExif" : false,
                      "filterMatchedContent" : false,
                      "antivirus" : false,
                      "replacementString" : "",
                      "allowInvalid" : false,
                      "descrption" : "Slack Integ Id",
                      "secret" : false,
                      "preserveCharsLimit" : 10,
                      "trim" : false,
                      "internalParam" : false,
                      "preserveChars" : "0,5",
                      "importUrl" : false,
                      "decrypt" : false
                    }
                  },
                  "defaultChannel" : {
                    "type" : [ "null", "object" ],
                    "additionalProperties" : false
                  }
                },
                "required" : [ "defaultChannel", "integDetail", "integId" ]
              }, {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "integDetail" : {
                    "$ref" : "./Slack.json#/components/schemas/teamIntegrationDetailResponse"
                  },
                  "integId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : {
                      "removeExif" : false,
                      "filterMatchedContent" : false,
                      "antivirus" : false,
                      "replacementString" : "",
                      "allowInvalid" : false,
                      "descrption" : "Slack Integ Id",
                      "secret" : false,
                      "preserveCharsLimit" : 10,
                      "trim" : false,
                      "internalParam" : false,
                      "preserveChars" : "0,5",
                      "importUrl" : false,
                      "decrypt" : false
                    }
                  },
                  "defaultChannel" : {
                    "type" : [ "null", "object" ],
                    "additionalProperties" : false
                  }
                },
                "required" : [ "defaultChannel", "integDetail", "integId" ]
              }, {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "integDetail" : {
                    "$ref" : "./Slack.json#/components/schemas/teamIntegrationDetailResponse"
                  },
                  "integId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : {
                      "removeExif" : false,
                      "filterMatchedContent" : false,
                      "antivirus" : false,
                      "replacementString" : "",
                      "allowInvalid" : false,
                      "descrption" : "Slack Integ Id",
                      "secret" : false,
                      "preserveCharsLimit" : 10,
                      "trim" : false,
                      "internalParam" : false,
                      "preserveChars" : "0,5",
                      "importUrl" : false,
                      "decrypt" : false
                    }
                  },
                  "departmentChannelMapping" : {
                    "$ref" : "./Slack.json#/components/schemas/departmentChannelMappingArray"
                  }
                },
                "required" : [ "departmentChannelMapping", "integDetail", "integId" ]
              }, {
                "type" : [ "null", "object" ],
                "additionalProperties" : false,
                "properties" : {
                  "integDetail" : {
                    "$ref" : "./Slack.json#/components/schemas/teamIntegrationDetailResponse"
                  },
                  "integId" : {
                    "type" : [ "string", "null", "integer" ],
                    "format" : "int64",
                    "pattern" : "([0-9]+)",
                    "x-custom-parameters-attributes" : {
                      "removeExif" : false,
                      "filterMatchedContent" : false,
                      "antivirus" : false,
                      "replacementString" : "",
                      "allowInvalid" : false,
                      "descrption" : "Slack Integ Id",
                      "secret" : false,
                      "preserveCharsLimit" : 10,
                      "trim" : false,
                      "internalParam" : false,
                      "preserveChars" : "0,5",
                      "importUrl" : false,
                      "decrypt" : false
                    }
                  }
                },
                "required" : [ "integDetail", "integId" ]
              } ]
            },
            "examples" : {
              "Valid responses Definitions" : {
                "value" : {
                  "teamName" : "helpdeskcorp.slack.com",
                  "mappedchannels" : [ "#champ", "#desk", "#Crm" ],
                  "defaultchannel" : "#champ",
                  "displayName" : "Help Desk Corp",
                  "notifyOn" : {
                    "ticketClose" : true,
                    "ticketCreate" : true,
                    "ticketAssignee" : false,
                    "accNotify" : true
                  },
                  "isEnabled" : true,
                  "logo" : "https://slack.com/team1",
                  "slackchannels" : [ "#champ", "#facebook", "#incoming", "#outgoing", "#zsdesk", "#supportnotify" ],
                  "id" : "1000000021010",
                  "departmentChannelMapping" : [ {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : true,
                    "channel" : "#champ"
                  }, {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : true,
                    "channel" : "#zohocrm"
                  }, {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : false,
                    "channel" : "#proj"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-response-attributes" : {
          "disable-safe-headers" : "[]"
        }
      }
    },
    "parameters" : {
      "integId" : {
        "name" : "integId",
        "in" : "path",
        "required" : true,
        "style" : "simple",
        "explode" : false,
        "schema" : {
          "type" : [ "string", "null", "integer" ],
          "format" : "int64",
          "pattern" : "([0-9]+)"
        }
      }
    },
    "requestBodies" : {
      "updateTeamIntegrationRequestBody" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "notifyOn" : {
                  "type" : [ "null", "object" ],
                  "additionalProperties" : false,
                  "maxProperties" : 10,
                  "minProperties" : 10,
                  "properties" : {
                    "ticketClose" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketBP" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketMove" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketComment" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketStatus" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketRating" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketEscalation" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketCreate" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketAssignee" : {
                      "type" : [ "boolean", "null" ]
                    },
                    "ticketReopen" : {
                      "type" : [ "boolean", "null" ]
                    }
                  },
                  "required" : [ "ticketAssignee", "ticketBP", "ticketClose", "ticketComment", "ticketCreate", "ticketEscalation", "ticketMove", "ticketRating", "ticketReopen", "ticketStatus" ]
                },
                "integId" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "pattern" : "([0-9]+)"
                }
              }
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "defaultchannel" : "#champ",
                  "isDepartmentChannelMapEnabled" : true,
                  "notifyOn" : {
                    "ticketClose" : true,
                    "ticketCreate" : true,
                    "ticketAssignee" : false
                  },
                  "isEnabled" : true,
                  "id" : "1000000021010",
                  "departmentChannelMapping" : [ {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : true,
                    "channel" : "#champ"
                  }, {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : true,
                    "channel" : "#zohocrm"
                  }, {
                    "departmentId" : "17364000000298215",
                    "isEnabled" : false,
                    "channel" : "#proj"
                  } ]
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      },
      "updateSlackTeamIntegrationStatusJsonRequestBody" : {
        "content" : {
          "application/json" : {
            "schema" : {
              "type" : [ "null", "object" ],
              "additionalProperties" : false,
              "properties" : {
                "isEnabled" : {
                  "type" : [ "boolean", "null" ]
                },
                "integId" : {
                  "type" : [ "string", "null", "integer" ],
                  "format" : "int64",
                  "pattern" : "([0-9]+)"
                }
              },
              "required" : [ "integId", "isEnabled" ]
            },
            "examples" : {
              "Valid requestBody Definitions" : {
                "value" : {
                  "isEnabled" : true
                }
              }
            }
          }
        },
        "x-custom-request-body-attributes" : {
          "non-empty" : false,
          "allow-invalid" : false
        }
      }
    },
    "securitySchemes" : {
      "cookie-auth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/cookie-auth"
      },
      "org-oauth" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/org-oauth"
      },
      "iam-oauth2-schema" : {
        "$ref" : "../common/Common.json#/components/securitySchemes/iam-oauth2-schema"
      }
    }
  },
  "x-entity" : "Slack"
}